#PRODUCTS
products:
  properties:
    product_id:
      type: number
      unique: true
      minLength: 5
      maxLength: 255
    name:
      type: number
      required: true
      minLength: 5
      maxLength: 255
    description:
      type: number
      required: true
      minLength: 5
      maxLength: 255
    price:
      type: number
      required: true
      minLength: 5
      maxLength: 255
    quantity:
      type: number
      default: 1
      min: 1
      max: 1000 || UPON_SPECIAL REQUEST

#USERS
users:
  properties:
    user_id:
      type: number
      unique: true
    firstName:
      type: string
      required: true
      minLength: 5
      maxLength: 255
    lastName:
      type: string
      required: true
      minLength: 5
      maxLength: 255
    email:
      type: string
      unique: true
      required: true
      minLength: 5
      maxLength: 255
    password:
      type: string
      required: true
      minLength: 5
      maxLength: 255
    phoneNumber:
      type: string
      required: true
      minLength: 5
      maxLength: 255
    shipping:
      firstName:
        type: string
        required: true
        minLength: 5
        maxLength: 255
      lastName:
        type: string
        required: true
        minLength: 5
        maxLength: 255
      address1:
        type: string
        required: true
        minLength: 5
        maxLength: 255
      address2:
        type: string
        required: true
        minLength: 5
        maxLength: 255
      city:
        type: string
        required: true
        minLength: 5
        maxLength: 255
      state:
        type: string
        required: true
        minLength: 5
        maxLength: 255
      zipCode:
        type: string
        required: true
        minLength: 5
        maxLength: 255
    billing:
      firstName:
        type: string
        required: true
        minLength: 5
        maxLength: 255
      lastName:
        type: string
        required: true
        minLength: 5
        maxLength: 255
      address1:
        type: string
        required: true
        minLength: 5
        maxLength: 255
      address2:
        type: string
        required: true
        minLength: 5
        maxLength: 255
      city:
        type: string
        required: true
        minLength: 5
        maxLength: 255
      state:
        type: string
        required: true
        minLength: 5
        maxLength: 255
      zipCode:
        type: string
        required: true
        minLength: 5
        maxLength: 255
      phoneNumber:
        type: string
        required: true
        minLength: 5
        maxLength: 255
    user_orders:
      type: array

#ORDERS
orders:
  properties:
    invoice_id:
      type: number
      unique: true
    description:
      type: string
      minLength: 5
      maxLength: 255
    line_items:
      type: array
      items:
        - product_id:
            type: number
            unique: true
            minLength: 5
            maxLength: 255
          name:
            type: number
            required: true
            minLength: 5
            maxLength: 255
          description:
            type: number
            required: true
            minLength: 5
            maxLength: 255
          price:
            type: number
            required: true
            minLength: 5
            maxLength: 255
          quantity:
#checkout

